"""update tokens model 2

Revision ID: 7aab010be8d7
Revises: 9d5bd35fab25
Create Date: 2026-06-05 15:02:09.528374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aab010be8d7'
down_revision: Union[str, Sequence[str], None] = '9d5bd35fab25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('refresh_token', sa.String(), nullable=False))
    op.add_column('tokens', sa.Column('revoked', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_tokens_token'), table_name='tokens')
    op.create_index(op.f('ix_tokens_refresh_token'), 'tokens', ['refresh_token'], unique=True)
    op.drop_column('tokens', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tokens_refresh_token'), table_name='tokens')
    op.create_index(op.f('ix_tokens_token'), 'tokens', ['token'], unique=True)
    op.drop_column('tokens', 'revoked')
    op.drop_column('tokens', 'refresh_token')
    # ### end Alembic commands ###
