"""add foreign key indexes

Revision ID: ed032022678a
Revises: 8cf80a3e4be9
Create Date: 2026-06-03 14:50:56.624522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed032022678a'
down_revision: Union[str, Sequence[str], None] = '8cf80a3e4be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###
